version: 0.2

env:
  variables:
    REPOSITORY_URI: "701622287110.dkr.ecr.ap-northeast-2.amazonaws.com/dev/dev-app"

phases:
  pre_build:
    commands:
      - echo "로그인 to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export IMAGE_TAG=`date +%Y%m%d%H%M%S`

  build:
    commands:
      - echo "Downloading system deps and wheelhouse from S3..."
      - aws s3 cp s3://haewon-dependency/system-deps/latest/debs.tar.gz ./debs.tar.gz
      - mkdir -p ./debs && tar -xzf debs.tar.gz -C ./debs
      - aws s3 cp s3://haewon-dependency/haewon/latest/wheelhouse.tar.gz ./wheelhouse.tar.gz
      - mkdir -p ./wheelhouse && tar -xzf wheelhouse.tar.gz -C ./wheelhouse
      - echo "Building Docker image with nginx..."
      - docker build \
          --build-arg DEBS_DIR=debs \
          --build-arg WHEELHOUSE_DIR=wheelhouse \
          -t dev/dev-app:latest .
      - docker tag dev/dev-app:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Image pushed: ${REPOSITORY_URI}:${IMAGE_TAG}"
      - echo ${REPOSITORY_URI}:${IMAGE_TAG} > image_tag.txt

artifacts:
  files:
    - image_tag.txt

