version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11   # CodeBuild 런타임에 맞는 파이썬 버전
    commands:
      - echo "Upgrading pip, setuptools, wheel..."
      - pip install --upgrade pip setuptools wheel

  build:
    commands:
      - echo "Downloading Python dependencies as wheels..."
      - pip download -r django-project/requirements.txt -d wheelhouse
      - echo "Packaging wheelhouse..."
      - tar -czf wheelhouse.tar.gz wheelhouse
      - |
        COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-10)
        echo "Uploading to S3 with commit hash: $COMMIT_HASH"
        aws s3 cp wheelhouse.tar.gz s3://haewon-dependency/haewon/$COMMIT_HASH/
        aws s3 cp wheelhouse.tar.gz s3://haewon-dependency/haewon/latest/wheelhouse.tar.gz

artifacts:
  files:
    - wheelhouse.tar.gz

